# Generated by Django 6.0.1 on 2026-02-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_card_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='UAH', max_length=3),
        ),
    ]
