# Generated by Django 6.0.1 on 2026-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CART', 'У кошику'), ('PENDING', 'Очікує підтвердження'), ('ACCEPTED', 'Прийнято продавцем'), ('COMPLETED', 'Завершено')], default='CART', max_length=20),
        ),
    ]
